### ISSUE TITLE
CoreConfig type handling not catching types not completely typed out

### ISSUE THREAD

**Issue by robertson-mark** [USDA-ARS-NWRC/inicheck#20]
* inicheck version: 0.3.5
* Python version: 3.5
* Operating System: 

### Description

Had incorrect type in coreconfig.ini,   type = CriticalFile, and the result was a warning with unregistered option.

**Comment by micahjohnson150** [comment]
Mark found that when he provided a totally misspelled  type it would throw the appropriate error, If the spelling was an incomplete spelling of an appropriate type it would work but only mention it was an unregistered option.
