### ISSUE TITLE
listed not always working as type

### ISSUE THREAD

**Issue by zuhlmann** [USDA-ARS-NWRC/inicheck#23]
* inicheck version:  0.3.5
* Python version:
* Operating System:

### Description

ValueError: 

Section histogram_outliers at item threshold_histogram_space attempted to use undefined type name 'ed float' which has no checker associated.
Available checkers are:

**Comment by micahjohnson150** [comment]
This was addressed with the fixes in #34 . And has pretty solid testing on it now. Closing.
