### ISSUE TITLE
the item values are apparently case sensitive when comparing options

### ISSUE THREAD

**Issue by etrujil** [USDA-ARS-NWRC/inicheck#31]
* inicheck version: Dunno
* Python version:
* Operating System: ubuntu 18.04

### Description
see title. In the convig file under awsm system variables

### What I Did
see title

```
@micahjohnson150 
```
Your favorite beta tester

**Comment by micahjohnson150** [comment]
This is due to [check_conifg Line 114 in tools.py ](url) https://github.com/USDA-ARS-NWRC/inicheck/blob/86bc77c92e876d547b457a76081decbfcdfedd4f/inicheck/tools.py#L114


The correct solution is to always check the lower case version of it. And confirm that the options are all lower.

**Comment by micahjohnson150** [comment]
Actuall issue that triggered this:

the variable SWI (in caps) triggers an error, works with swi (lower case)
