### ISSUE TITLE
inicheck not installing

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/inicheck#43]
* inicheck version: 0.7.6
* Python version: 3.5.2

Pandas came out with an update to version 1.0 and it seems that with Python 3.5.2, `pandas` doesn't want to install. Have tested with Python 3.6.9 and it doesn't have this problem. Both tested with fresh virtual env.

**Comment by scotthavens** [comment]
PR #42 will solve this issue

**Comment by micahjohnson150** [comment]
officially fixed in 0.7.7 by closing PR #42
