### ISSUE TITLE
Move tests completely over to pytest

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/inicheck#58]
* inicheck version: 0.9.0

### Description

pytest was used as the runner for running tests when the project was created, but I ended up using unittests for creating tests. I have recently been using pytest and find it a little bit cleaner and I have really found a lot of power in parametrizing tests. What I would like to do is:

1. Move completely away from unittests for simplicity and consistency.
2. Parameterize some of the tests to DRY out test code.

@scotthavens @jomey any qualms with this idea?

**Comment by scotthavens** [comment]
I agree that pytest can be a bit cleaner for simpler projects. I've been using it with pysnobal and find it a bit easier. No qualms here.

**Comment by jomey** [comment]
Same experience here with `pytest`. The parametrization option makes for some powerful test suite :+1:

**Comment by micahjohnson150** [comment]
All test have been moved over to pytest and are parametrized. This fixed with PR #60
